apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-dep
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: test
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
